# Generated by Django 5.2.3 on 2025-06-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('telephone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='single', max_length=100)),
                ('preferred_work', models.CharField(choices=[('factory worker', 'FACTORY WORKER'), ('farm worker', 'FARM WORKER'), ('cleaner', 'CLEANER'), ('caretaker', 'CARETAKER'), ('chef', 'CHEF'), ('waiter', 'WAITER'), ('electrician', 'ELECTRICIAN'), ('plumber', 'PLUMBER'), ('security', 'SECURITY'), ('painter', 'PAINTER'), ('driver', 'DRIVER'), ('computer operator', 'COMPUTER OPERATOR'), ('laundry', 'LAUNDRY'), ('teacher', 'TEACHER'), ('nurse', 'NURSE'), ('forklift', 'FORKLIFT'), ('civil engineer', 'CIVIL ENGINEER'), ('mechanic', 'MECHANIC')], default='cleaner', max_length=100)),
                ('work_experience', models.CharField(max_length=10)),
                ('elegibility', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('traveling_experience', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
            ],
        ),
    ]
