# Generated by Django 5.2.3 on 2025-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='education',
            field=models.CharField(choices=[('high school', 'High School'), ('college', 'College'), ('university', 'University')], default='high school', max_length=50),
        ),
    ]
