# Generated by Django 5.2.3 on 2025-07-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='ghana_card',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='passport_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
