# Generated by Django 5.2.3 on 2025-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_form_ghana_card_form_passport_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
