# Generated by Django 5.2.3 on 2025-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
