# Generated by Django 5.2.3 on 2025-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
            ],
        ),
    ]
